# Generated by Django 3.2.11 on 2022-01-26 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dyspozytor',
            fields=[
                ('idDyspozytora', models.IntegerField(primary_key=True, serialize=False)),
                ('imieDyspozytora', models.CharField(max_length=50)),
                ('nazwiskoDyspozytora', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kierowca',
            fields=[
                ('idKierowcy', models.IntegerField(primary_key=True, serialize=False)),
                ('imieKierowcy', models.CharField(max_length=50)),
                ('nazwiskoKierowcy', models.CharField(max_length=50)),
                ('dlugoscGeoKierowcy', models.FloatField()),
                ('szerokoscGeoKierowcy', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('idKlienta', models.IntegerField(primary_key=True, serialize=False)),
                ('imieKlienta', models.CharField(max_length=50)),
                ('nrTelefonu', models.CharField(max_length=9)),
                ('dlugoscGeoKlienta', models.FloatField()),
                ('szerokoscGeoKlienta', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usluga',
            fields=[
                ('idUsluga', models.IntegerField(primary_key=True, serialize=False)),
                ('idDyspozytora', models.IntegerField()),
                ('dlugoscGeoCelu', models.FloatField()),
                ('szerokoscGeoCelu', models.FloatField()),
                ('idKierowcy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.kierowca')),
                ('idKlienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.klient')),
            ],
        ),
    ]
