# Generated by Django 3.2.11 on 2022-01-27 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usluga',
            name='statusRealizacji',
            field=models.IntegerField(choices=[(1, 'Rozpoczęto'), (2, 'W trakcie'), (3, 'Zakończono')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usluga',
            name='idKierowcy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxi.kierowca'),
        ),
    ]
