# Generated by Django 3.2.11 on 2022-01-28 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_auto_20220127_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dyspozytor',
            options={'verbose_name': 'Dyspozytor', 'verbose_name_plural': 'Dyspozytory'},
        ),
        migrations.AlterModelOptions(
            name='kierowca',
            options={'verbose_name': 'Kierowca', 'verbose_name_plural': 'Kierowcy'},
        ),
        migrations.AlterModelOptions(
            name='klient',
            options={'verbose_name': 'Klient', 'verbose_name_plural': 'Klienci'},
        ),
        migrations.AlterModelOptions(
            name='usluga',
            options={'verbose_name': 'Usluga', 'verbose_name_plural': 'Uslugi'},
        ),
        migrations.AlterField(
            model_name='usluga',
            name='idDyspozytora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.dyspozytor'),
        ),
        migrations.AlterField(
            model_name='usluga',
            name='statusRealizacji',
            field=models.IntegerField(choices=[(1, 'W trakcie'), (2, 'Zakonczono')]),
        ),
    ]
