# Generated by Django 3.2.11 on 2022-01-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_auto_20220128_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kierowca',
            name='dlugoscGeoKierowcy',
        ),
        migrations.RemoveField(
            model_name='kierowca',
            name='szerokoscGeoKierowcy',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='dlugoscGeoKlienta',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='szerokoscGeoKlienta',
        ),
        migrations.AddField(
            model_name='usluga',
            name='dlugoscGeoKlienta',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usluga',
            name='szerokoscGeoKlienta',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dyspozytor',
            name='idDyspozytora',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kierowca',
            name='idKierowcy',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='klient',
            name='idKlienta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usluga',
            name='dlugoscGeoCelu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usluga',
            name='idUsluga',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usluga',
            name='szerokoscGeoCelu',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
