# Generated by Django 3.2.11 on 2022-01-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0004_auto_20220128_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usluga',
            name='dlugoscGeoCelu',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usluga',
            name='dlugoscGeoKlienta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usluga',
            name='szerokoscGeoCelu',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usluga',
            name='szerokoscGeoKlienta',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
